### ISSUE TITLE
Completing Levels sometimes breaks sim

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/fraction-matcher#104]
Test device: PC Laptop

Operating System: Windows 10 v. 1803

Browser: Google Chrome v. 67.0.3396.99

Problem description: Upon completion of various levels the sim will break and nothing will be able to be clicked. When this occurs the cursor becomes locked in either the normal pointer or the finger pointer, however nothing can be done to the sim until the entire page is reloaded and all saved data is lost. I have not been able to determine the cause of this bug as it is inconsistent in when it takes effect. So far I have noticed that on completing levels 4, 5, 6, 7, and 8 the sim has been rendered unusable. Here is the error the console gives me when this bug occurs. 

```

Uncaught TypeError: Cannot read property 'detach' of null
    at Array.levelCompletedNodeContainer.Node.children.LevelCompletedNode.centerX (LevelNode.js?bust=1530133189296:500)
    at Emitter.emit (Emitter.js?bust=1530133189296:134)
    at PushButtonModel.fire (PushButtonModel.js?bust=1530133189296:146)
    at Array.<anonymous> (PushButtonModel.js?bust=1530133189296:83)
    at Emitter.emit2 (Emitter.js?bust=1530133189296:180)
    at Property._notifyListeners (Property.js?bust=1530133189296:282)
    at Property._setAndNotifyListeners (Property.js?bust=1530133189296:269)
    at Property.set (Property.js?bust=1530133189296:216)
    at Property.set value [as value] (Property.js?bust=1530133189296:311)
    at PressListener.release (PressListener.js?bust=1530133189296:469)

```
Liam has gotten this error on his mac when testing:

```
Uncaught TypeError: Cannot read property 'detach' of undefined
    at Array.levelCompletedNodeContainer.Node.children.LevelCompletedNode.centerX (LevelNode.js?bust=1530136584561:500)
    at Emitter.emit (Emitter.js?bust=1530136584561:134)
    at PushButtonModel.fire (PushButtonModel.js?bust=1530136584561:146)
    at Array.<anonymous> (PushButtonModel.js?bust=1530136584561:83)
    at Emitter.emit2 (Emitter.js?bust=1530136584561:180)
    at Property._notifyListeners (Property.js?bust=1530136584561:282)
    at Property._setAndNotifyListeners (Property.js?bust=1530136584561:269)
    at Property.set (Property.js?bust=1530136584561:216)
    at Property.set value [as value] (Property.js?bust=1530136584561:311)
    at PressListener.release (PressListener.js?bust=1530136584561:469)
levelCompletedNodeContainer.Node.children.LevelCompletedNode.centerX @ LevelNode.js?bust=1530136584561:500
emit @ Emitter.js?bust=1530136584561:134
fire @ PushButtonModel.js?bust=1530136584561:146
(anonymous) @ PushButtonModel.js?bust=1530136584561:83
emit2 @ Emitter.js?bust=1530136584561:180
_notifyListeners @ Property.js?bust=1530136584561:282
_setAndNotifyListeners @ Property.js?bust=1530136584561:269
set @ Property.js?bust=1530136584561:216
set value @ Property.js?bust=1530136584561:311
release @ PressListener.js?bust=1530136584561:469
up @ PressListener.js?bust=1530136584561:203
dispatchToListeners @ Input.js?bust=1530136584561:1352
dispatchEvent @ Input.js?bust=1530136584561:1308
upEvent @ Input.js?bust=1530136584561:1071
mouseUp @ Input.js?bust=1530136584561:511
pointerUp @ Input.js?bust=1530136584561:915
run @ BatchedDOMEvent.js?bust=1530136584561:59
fireBatchedEvents @ Input.js?bust=1530136584561:275
batchEvent @ Input.js?bust=1530136584561:236
batchWindowEvent @ BrowserEvents.js?bust=1530136584561:320
onpointerup @ BrowserEvents.js?bust=1530136584561:357
```

Steps to reproduce: Play any of level 4, 5, 6, 7, or 8 (of either game, I have yet to see it break after completing levels 1, 2, or 3). After completing the game the scoreboard will pop us as intended, once continue is hit it will now redirect to the choose level screen, however nothing can be manipulated. This bug does not occur every time so you might have to try certain levels multiple times in order to see the effects. 

Screenshot: I have attached a gif of the game screen after the bug has taken effect, as you can see the cursor does not change type and I can not click anything on the sim screen.
![fm_breaks](https://user-images.githubusercontent.com/30352536/42004154-dd96d6b6-7a2b-11e8-826c-33d249dbae21.gif)

<details>
<summary>
Troubleshooting Info:
</summary>
Name: ‪Build an Atom‬
URL: https://bayes.colorado.edu/dev/html/build-an-atom/1.6.0/build-an-atom_en.html
Version: 1.6.0 2017-07-27 20:42:10 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
Language: en-US
Window: 1280x615
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"5c3f9204","branch":"HEAD"},"axon":{"sha":"fd28f6a0","branch":"HEAD"},"babel":{"sha":"a53d7c25","branch":"master"},"brand":{"sha":"b630f897","branch":"HEAD"},"build-an-atom":{"sha":"04930009","branch":"1.6"},"chipper":{"sha":"80ecc40f","branch":"HEAD"},"dot":{"sha":"f7d9de8b","branch":"HEAD"},"joist":{"sha":"d4e70ec7","branch":"HEAD"},"kite":{"sha":"41ac3b7a","branch":"HEAD"},"phet-core":{"sha":"d8bec6c1","branch":"HEAD"},"phetcommon":{"sha":"7ec5d299","branch":"HEAD"},"query-string-machine":{"sha":"c74e454e","branch":"HEAD"},"scenery":{"sha":"a3198c07","branch":"HEAD"},"scenery-phet":{"sha":"effed588","branch":"HEAD"},"sherpa":{"sha":"f1937ecb","branch":"HEAD"},"shred":{"sha":"820bea97","branch":"HEAD"},"sun":{"sha":"e1d62999","branch":"HEAD"},"tandem":{"sha":"29cd4f63","branch":"HEAD"},"vegas":{"sha":"9d6265d2","branch":"HEAD"},"vibe":{"sha":"b69e96db","branch":"HEAD"}}
</details>

**Comment by zepumph** [comment]
Let me know if I can be any assistance.

**Comment by jonathanolson** [comment]
This doesn't happen with the new code changes, closing.
