### ISSUE TITLE
Font on 'Try Again' button odd looking in Chrome when window downsized

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/fraction-matcher#74]
Test device: 

Operating System: Win 7 64-bit

Browser: Chrome 35.0.1916.153

Problem description: Try Again button looks odd on Chrome when screen size is reduced. Almost reads as "Try A gain"

Steps to reproduce: Resize width of screen to roughly 1/2

Severity:

Screenshots:
![fraction matcher 1 0 0-rc 3 - google chrome_-07-11_11-10-05](https://cloud.githubusercontent.com/assets/5090275/3555993/7865ebd8-091e-11e4-8101-d4db2a67b56d.png)

![fraction matcher 1 0 0-rc 3 - google chrome_-07-11_11-13-28](https://cloud.githubusercontent.com/assets/5090275/3556017/bc2f3cd4-091e-11e4-84c0-fb230182567c.png)

Troubleshooting information (do not edit):
Name: Fraction Matcher
URL: http://www.colorado.edu/physics/phet/dev/html/fraction-matcher/1.0.0-rc.3/fraction-matcher_en.html
Version: 1.0.0-rc.3
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36
Language: en-US
Window: 790x790
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 10 uniform: 254
Texture: size: 16384 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 16384x16384
OES_texture_float: true

**Comment by ariel-phet** [comment]
No longer an issue, closing
