### ISSUE TITLE
replace LevelStartButtonDeprecated with LevelSelectionButton

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fraction-matcher#80]
See https://github.com/phetsims/vegas/issues/36

**Comment by samreid** [comment]
This should be re-evaluated as part of summer 2015 redeploys, unassigning until then.

**Comment by ariel-phet** [comment]
Please check on this @jonathanolson

**Comment by jonathanolson** [comment]
I'm exclusively using LevelSelectionButton, closing.
