### ISSUE TITLE
Do not require user to click "try again" 

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/fraction-matcher#82]
When a student gets a problem incorrect and the "try again" button appears, they must click it in order to move on. 

In other game sims we have stopped requiring a user to click that button- interaction with the sim has the same result of clicking "try again". 

I suggest we incorporate that interaction in Fraction Matcher to be consistent. In an interview, a student was not familiar with pressing "try again" and struggled to find it.

**Comment by ariel-phet** [comment]
Assigning to myself to discuss at developer meeting if this is a small task that could be incorporated soonish

**Comment by aadish** [comment]
@ariel-phet this has been fixed and would be good to have it tested.
What are the next steps on this
If the maintenance release has to be done next week then please assign it to @jbphet and if it can be done after that please assign it to me

**Comment by ariel-phet** [comment]
@aadish it can be done after next week.

**Comment by ariel-phet** [comment]
When you are ready making a testing task and assign it to me.

**Comment by aadish** [comment]
fixed and is live closing
