### ISSUE TITLE
why does fraction-matcher need .iml files?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fraction-matcher#85]
fraction-match.iml and fraction-common.iml are checked in. These are IntelliJ IDEA project files. 

.gitignore also doesn't look correct. It's missing files that all sims ignore (*.iml, .DS_Store
.DS_Store?), and it includes a bunch of IDEA files:

/.idea/.name
/.idea/codeStyleSettings.xml
/.idea/encodings.xml
/.idea/fraction-matcher.iml
/.idea/inspectionProfiles/Project_Default.xml
/.idea/inspectionProfiles/profiles_settings.xml
/.idea/jsLibraryMappings.xml
/.idea/jsLinters/jshint.xml
/.idea/misc.xml
/.idea/modules.xml
/.idea/scopes/scope_settings.xml
/.idea/vcs.xml
/.idea/workspace.xml

**Comment by samreid** [comment]
Fixed above, reassigned to @pixelzoom for a quick double check if anything else should be done here.

**Comment by pixelzoom** [comment]
Looks good, closing.
