### ISSUE TITLE
Text for "Score" overlap on Safari with ?stringTest=double

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/fraction-matcher#87]
Test device: Personal mac
Operating System: OSX 10.11
Browser: Safari 9.0
Problem description: "Score" overlaps itself in game scene 

Screenshots:
<img width="192" alt="screen shot 2016-01-21 at 10 10 06 am" src="https://cloud.githubusercontent.com/assets/5631059/12488198/a615efd0-c027-11e5-9f28-b0625e8413c2.png">

Troubleshooting information (do not edit):
Name: ‪Fraction Matcher‬:‪Fraction Matcher‬
URL: http://phettest.colorado.edu/fraction-matcher/fraction-matcher_en.html?ea&brand=phet&stringTest=double
Version: 1.0.0 (require.js)
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11) AppleWebKit/601.1.56 (KHTML, like Gecko) Version/9.0 Safari/601.1.56
Language: en-us
Window: 1240x712
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (2.1 INTEL-10.8.77)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

Testing for task https://github.com/phetsims/tasks/issues/479

**Comment by samreid** [comment]
I believe this double blurry text has been resolved, @jessegreenberg or @jonathanolson correct me if I'm wrong!
