### ISSUE TITLE
Wrong answer buttons layer over bottom of the fraction measurer

### ISSUE THREAD

**Issue by phet-steele** [phetsims/fraction-matcher#88]
"Try Again" and "Show Answer" buttons aren't handled too gracefully with ?stringTest=double. Even though they don't negatively affect functionality, thought I'd point it out: 

![fm dubs](https://cloud.githubusercontent.com/assets/5863899/12492181/4ead65ce-c03c-11e5-9ad0-1c02d9cc919a.PNG)

Tested on phettest with Win 8.1 and FF. For phetsims/tasks/issues/479

Troubleshooting information:
Name: ‪Fraction Matcher‬:‪Fraction Matcher‬
URL: http://phettest.colorado.edu/fraction-matcher/fraction-matcher_en.html?ea&brand=phet&stringTest=double
Version: 1.0.0 (require.js)
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 28 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by samreid** [comment]
Fixed in https://github.com/phetsims/fraction-matcher/issues/92, closing.
