### ISSUE TITLE
Are we translating the = sign?

### ISSUE THREAD

**Issue by samreid** [phetsims/fraction-matcher#91]
I thought not but it was already like this, @ariel-phet can you comment:

![image](https://cloud.githubusercontent.com/assets/679486/13507214/f23b3978-e13e-11e5-838a-cef59754d1e6.png)

**Comment by ariel-phet** [comment]
I think the "equals" sign is universal enough that we do not need to translate

**Comment by samreid** [comment]
Fixed, closing.
