### ISSUE TITLE
Deploy for S2015R

### ISSUE THREAD

**Issue by samreid** [phetsims/fraction-matcher#92]
After @ariel-phet reviews #90, we can proceed with the next steps in the deployment, which will entail:

- [x] build with stable shas and in a branch, and updated version number
- [x] developer testing
- [ ] RC testing
- [ ] publish

**Comment by samreid** [comment]
Updated to latest stable shas, pushed a new 1.1 branch and updated version number

**Comment by samreid** [comment]
I used:
`
grunt checkout-shas
grunt
grunt deploy-rc
`
to deploy http://www.colorado.edu/physics/phet/dev/html/fraction-matcher/1.1.0-dev.1/fraction-matcher_en.html

I'll personally spot test it on:

- [ ] OS X Chrome
- [ ] OS X Firefox
- [ ] OS X Safari
- [ ] iPad3 Safari
- [ ] Win IE
- [ ] Win Firefox
- [ ] Win Chrome

**Comment by samreid** [comment]
Button widths are broken in this version:

![image](https://cloud.githubusercontent.com/assets/679486/13670404/f8dc7290-e686-11e5-85a2-f1078987c708.png)

This means the sun change made in https://github.com/phetsims/sun/issues/232 did not get captured in this sha.  I'll need to update that sha before proceeding.

**Comment by samreid** [comment]
Aside from the TextPushButton maxWidth change, the other changes in sun/master are: RectangularPushButton accessiblepeer changes, carousel changes and hslider changes, none of which are used by Fraction Matcher, so I'll get master as a new sha.

**Comment by samreid** [comment]
The sha is `7d41341a93434e8499ee6f6d994973b099a2f278`

**Comment by samreid** [comment]
Something is wrong, I typed 

```
$ grunt deploy-rc
Running "deploy-rc" task
```

a few minutes ago and its not doing anything.  

Now it says: Warning: Build request failed with status code 503. Use --force to continue.

**Comment by samreid** [comment]
It seems the build-server may be having troubles.

**Comment by samreid** [comment]
I used grunt deploy-dev for now and will create an issue for the potential build server problem:
http://www.colorado.edu/physics/phet/dev/html/fraction-matcher/1.1.0-dev.2/fraction-matcher_en.html

**Comment by samreid** [comment]
Following the docs, I'll try:

```
sudo /etc/init.d/build-server restart
```

It reported:

```
Stopping build-server:                                     [  OK  ]
Starting build-server:                                     [  OK  ]
```

**Comment by samreid** [comment]
Now I can send commands to the build server again, though I am not sure why it failed in the first place.  Are there logs we can/should look at?

**Comment by samreid** [comment]
Here's the version published with the build-server:

http://www.colorado.edu/physics/phet/dev/html/fraction-matcher/1.1.0-dev.3/fraction-matcher_en.html

**Comment by samreid** [comment]
Looks like the sun sha is fixed in this new version:

![image](https://cloud.githubusercontent.com/assets/679486/13671103/15281a68-e68b-11e5-880f-0fc1a2e2dcca.png)

**Comment by samreid** [comment]
Fixed version deployed here for further testing:
http://www.colorado.edu/physics/phet/dev/html/fraction-matcher/1.1.0-dev.4/fraction-matcher_en.html

**Comment by samreid** [comment]
I'm seeing this text now:

![image](https://cloud.githubusercontent.com/assets/679486/13672505/4e58f94a-e692-11e5-99a6-62c426b35b07.png)

**Comment by samreid** [comment]
Ah, I guess I'll need that sha too.

**Comment by samreid** [comment]
Comparing scenery-phet master to the sha, I see a safe change to ResetAllButton, the change for the FaceWithPointsNode and changes to the following other files which are unused in this sim:

GaugeNode
HeaterCoolerFront
ParametricSpringNode
SubSupText

So it will be safe to get the new sha for scenery-phet.

**Comment by samreid** [comment]
I'll get scenery-phet bdb9335c9bd24ca4e088a49221d8eeadf71a3bf8 which is the version that includes FaceWithPointsNode changes.

**Comment by samreid** [comment]
And I'll need @jonathanolson's lint fix in 3d7d9459ae6e332d58f14fd7f51e443ba388ccab

**Comment by samreid** [comment]
http://www.colorado.edu/physics/phet/dev/html/fraction-matcher/1.1.0-dev.5/fraction-matcher_en.html

Developer spot tests:
- [ ] OS X Chrome
- [ ] OS X Firefox
- [ ] OS X Safari
- [ ] iPad3 Safari
- [ ] Win IE
- [ ] Win Firefox
- [ ] Win Chrome

**Comment by samreid** [comment]
No problems detected in developer spot tests across platforms, the next step is for me to create an RC.  I think this means changing the version number to rc.1 and running grunt + grunt deploy-rc.

**Comment by samreid** [comment]
Here's the RC:
http://www.colorado.edu/physics/phet/dev/html/fraction-matcher/1.1.0-rc.1/fraction-matcher_en.html

I manually diffed vs 1.1.0-dev.5 and verified the changes are minimal, so this corresponds closely to what I have spot checked.  I'll create a tasks issue now.

**Comment by samreid** [comment]
on hold during RC testing.

**Comment by phet-steele** [comment]
@samreid looks like the screenshot in https://github.com/phetsims/fraction-matcher/issues/92#issuecomment-194843037 is the fix for https://github.com/phetsims/fraction-matcher/issues/88?

**Comment by phet-steele** [comment]
@samreid @ariel-phet are we not going to address that neither the "Level", "Score:", "My Matches", or level completion pop up strings have a set max width?

These are really only an issue with stringTest=long
![long fraction](https://cloud.githubusercontent.com/assets/5863899/13711307/0db53662-e77b-11e5-97f8-8489fff7e5c0.PNG)

But this one still expands with stringTest=double, and may be worth it to fix:
![long fraction win](https://cloud.githubusercontent.com/assets/5863899/13711324/2369c298-e77b-11e5-999f-28ee1b579e6d.PNG)

How it's supposed to look:
![normal fraction win](https://cloud.githubusercontent.com/assets/5863899/13711375/7ae1379a-e77b-11e5-828b-7574fd912be2.PNG)

**Comment by samreid** [comment]
I'll leave this up to @ariel-phet, reassigning.

**Comment by ariel-phet** [comment]
@phet-steele I find those unlikely to be an issue (and I am fine with the level completion expanding, since it does not go off screen or such). The all "pass" ?stringTest=double and I think we can trust our translators not to do something too whacky beyond that.

**Comment by samreid** [comment]
On hold until I hear from @ariel-phet about https://github.com/phetsims/fraction-matcher/issues/95

**Comment by samreid** [comment]
The only fix from the RC that needs updating is solely in the fraction-matcher repo, so we can keep the pre-existing SHAs from the last RC.  This should make RC testing go very smoothly, or even let us get by with a mere spot test instead of full RC.  I'll publish shortly and confer with @ariel-phet about testing.

**Comment by samreid** [comment]
RC2 published at http://www.colorado.edu/physics/phet/dev/html/fraction-matcher/1.1.0-rc.2/ and I manually diffed the minified code to verify that all of the changes were as desired (from the recent fixes found in the last RC).

**Comment by samreid** [comment]
RC2 was confirmed good to go, now we can publish this on figaro.

**Comment by samreid** [comment]
I manually confirmed that the existing screenshot is still consistent with the latest version of the simulation, so it doesn't need to be regenerated.

**Comment by samreid** [comment]
I followed the steps in the deployment guide and fraction matcher 1.1.0 has been published on figaro.  I'll check it off the checklist in https://github.com/phetsims/tasks/issues/476 and email the team in case other notifications need to be sent out (such as notifying translators).

**Comment by samreid** [comment]
I also manually diffed RC2 with 1.1.0 and verified that they only differed in build timestamp and version number.
