### ISSUE TITLE
RTL support for choose your level strings

### ISSUE THREAD

**Issue by phet-steele** [phetsims/fraction-matcher#96]
@samreid while most of these strings have rtl support, maybe we should also make 'mixedNumbersChooseYourLevel' and 'fractionsChooseYourLevel' strings a pattern? For phetsims/tasks/issues/541.

**Comment by phet-steele** [comment]
Currently their values are along the lines of "Mixed Numbers: Choose your level!". Could they be "Mixed Numbers: {0}" and "Fractions: {0}"?

**Comment by phet-steele** [comment]
Actually I've convinced myself that this is entirely unnecessary. @samreid reopen if you want to.

**Comment by samreid** [comment]
The strings are:

```js
  "mixedNumbersChooseYourLevel": {
    "value": "Mixed Numbers: Choose your level!"
  },
  "fractionsChooseYourLevel": {
    "value": "Fractions: Choose your level!"
  }
```

so the translators already have complete control over the word order.
