### ISSUE TITLE
directory structure doesn't doesn't match PhET conventions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fraction-matcher#99]
While working on https://github.com/phetsims/joist/issues/307, I noticed that the directory structure of fraction-matcher doesn't match PhET conventions. There should be a parent directory for its single screen.

**Comment by ariel-phet** [comment]
@jonathanolson has this been addressed?

**Comment by jonathanolson** [comment]
This was addressed with the recent code changes to match the sim-suite style.
